### ISSUE TITLE
WMPWSZConvert.dpr(1) Fatal: Line too long (more than 1023 characters)

### ISSUE THREAD

**Issue by Thyristor-Chopper** [tdebaets/wmp-wsz-format#1]
![ds](https://github.com/tdebaets/wmp-wsz-format/assets/76606635/8953296f-3e0f-4bdf-a203-b2911c03554d)

Using Windows XP SP3 with Delphi 4 Professional installed. I don't see any lines in your source exceeding even 255 characters.

Also tried converting your source to ASCII from UTF-8 but doesn't work

I want to add the Skin chooser tab to my Windows Media Player 10 Beta

**Comment by tdebaets** [comment]
Is it possible that you cloned the project with Linux line endings? Delphi probably only supports Windows line endings.

**Comment by Thyristor-Chopper** [comment]
now I get:
```
Borland Delphi  Version 12.0  Copyright (c) 1983,98 Inprise Corporation
D:\wmp-wsz-format\common\Delphi\LibUser\TypInfoNew.pas(69) Fatal: Internal error
: URW527
```

google search: no information about URW527 at all. In duckduckgo: there is a site with title "Help!, I am victim of URW527 (using D4) - delphi" but the site is down and not connectable.

notice TypInfoNew.pas has only 68 lines.

Or is there a compiled binary of the converter?

**Comment by tdebaets** [comment]
Do you have all four update packs for Delphi 4 installed on your system?

**Comment by tdebaets** [comment]
If you're still having trouble to compile, I have just created a release that contains a compiled binary, let me know if it works.

**Comment by Thyristor-Chopper** [comment]
Thanks. I was looking for the Delphi update pack but I couldn't find any downloads for it

**Comment by tdebaets** [comment]
Just in case you or anyone else still needs them, I have uploaded the Delphi 4 update packs to my website:

- https://bmproductions.fixnum.org/software/delphi/d4cupd2.exe
- https://bmproductions.fixnum.org/software/delphi/d4cupd3.exe
- https://bmproductions.fixnum.org/software/delphi/d4u3menu.zip

I don't have the 1st update pack either but that update pack isn't a requirement to install pack 2 (I assume that pack 2 is cumulative).

**Comment by Thyristor-Chopper** [comment]
Wait you were bmproductions? I just want to notify you that most features of WMP Plus! plugin works fine on Windows Media Player 9 although it's not officially supported.

(I'm using title bar customization and hotkeys)

![dsf](https://github.com/user-attachments/assets/2dc4115f-a133-4396-93ba-62c522ff0df2)
